version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_USER: ${DB_USER:-todo_admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-securepassword123}
      POSTGRES_DB: ${DB_NAME:-todo_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - todo_network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-todo_admin} -d ${DB_NAME:-todo_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: todo_redis
    command: redis-server --requirepass ${REDIS_PASSWORD:-redispassword123}
    volumes:
      - redis_data:/data
    networks:
      - todo_network
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--auth", "${REDIS_PASSWORD:-redispassword123}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  todo_network:
    driver: bridge